name: life_track
description: "Aplicación para seguimiento de hábitos, relaciones y finanzas personales."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  image_picker: ^1.0.7
  fl_chart: ^0.66.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.0.0
  table_calendar: ^3.0.9
  uuid: ^4.3.3
  local_auth: ^2.3.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
